# Generated by Django 5.0.14 on 2026-07-01 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_courier_status_order_customer_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cod', 'Cash on Delivery'), ('mobile', 'Mobile Banking'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('gateway', 'Online Gateway')], max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('account_details', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CODApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approver_username', models.CharField(max_length=150)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cod_approvals', to='orders.order')),
            ],
        ),
    ]
