# Generated by Django 5.0.14 on 2026-07-14 15:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customerprofile_is_pinned'),
        ('orders', '0004_district_thana'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public-facing one-time-use token embedded in the checkout link.', unique=True)),
                ('variant_sku', models.CharField(help_text='Copied SKU from ProductVariant at time of creation. Decoupled from variant.', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(blank=True, help_text='Snapshot of the product name for display in checkout link messages.', max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot of the selling price at time of draft creation.', max_digits=10)),
                ('image_url', models.URLField(blank=True, help_text='Public URL of the matched product image for display in checkout.', max_length=1000)),
                ('source_channel', models.CharField(blank=True, help_text='The omnichannel platform that triggered this draft (e.g. instagram, whatsapp).', max_length=20)),
                ('thread_id', models.IntegerField(blank=True, help_text='Foreign key to cyberbrain.ChatThread (stored as int to avoid circular import).', null=True)),
                ('converted', models.BooleanField(db_index=True, default=False, help_text='Set True once a real Order is placed. Prevents double-use of the token.')),
                ('expires_at', models.DateTimeField(help_text='Hard expiry timestamp (30 minutes from creation). Enforced at application layer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='The CRM customer who triggered this draft via chat.', on_delete=django.db.models.deletion.CASCADE, related_name='draft_carts', to='crm.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'converted'], name='orders_draf_token_1694aa_idx'), models.Index(fields=['customer', 'created_at'], name='orders_draf_custome_91b74a_idx')],
            },
        ),
    ]
