# Generated by Django 5.0.14 on 2026-07-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_screenshot_to_order_pipeline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
