# Generated by Django 5.0.14 on 2026-07-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftcart',
            name='thread_id',
        ),
    ]
