# Generated by Django 5.0.14 on 2026-08-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_unlogged_draftcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraftCart',
        ),
    ]
