# Generated by Django 5.0.14 on 2026-08-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_draftcart_unlogged'),
        ('orders', '0010_order_orders_orde_user_id_37fed6_idx_and_more'),
    ]

    operations = [
    ]
