# Generated by Django 5.0.14 on 2026-08-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_courier_consignment_id_order_courier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issue_status',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('review', 'In Review'), ('pending', 'Pending'), ('hold', 'Hold'), ('approval_pending', 'Approval Pending'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('rto', 'RTO')], default='placed', max_length=30),
        ),
    ]
