# Generated by Django 5.0.14 on 2026-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_print_ready',
            field=models.BooleanField(default=False),
        ),
    ]
