# Generated by Django 5.0.14 on 2026-07-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music/tracks/')),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_art', models.FileField(blank=True, null=True, upload_to='music/covers/')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
