# Generated by Django 5.0.14 on 2026-08-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='cover_art',
        ),
        migrations.RemoveField(
            model_name='track',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='track',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Track duration in seconds (auto-populated by migrate_audio command).', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload MP3/OGG file. This takes priority over audio_url when set.', null=True, upload_to='music/tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.URLField(blank=True, help_text='External audio URL. Used only as fallback when audio_file is not set.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
