# Generated by Django 5.0.14 on 2026-08-12 19:20

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_update_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'bKash Business', 'DBBL Savings'", max_length=100)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('mobile_banking', 'Mobile Banking'), ('cash', 'Cash in Hand')], default='bank', max_length=20)),
                ('provider', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('upay', 'Upay'), ('dbbl', 'Dutch-Bangla Bank (DBBL)'), ('brac_bank', 'BRAC Bank'), ('dutch_bangla', 'Dutch Bangla'), ('islami_bank', 'Islami Bank'), ('city_bank', 'City Bank'), ('eastern_bank', 'Eastern Bank'), ('ucb', 'United Commercial Bank'), ('prime_bank', 'Prime Bank'), ('trust_bank', 'Trust Bank'), ('other', 'Other')], default='other', max_length=30)),
                ('account_number', models.CharField(help_text='Bank account no. or mobile number', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, help_text='Balance as per bank at start of period', max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, help_text='Balance as per bank at end of period', max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(help_text="Bank's own description/narration", max_length=255)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Money In)'), ('debit', 'Debit (Money Out)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. Use transaction_type to determine direction.', max_digits=14)),
                ('reference', models.CharField(blank=True, default='', help_text='Cheque no., bKash TrxID, bank ref. etc.', max_length=100)),
                ('is_reconciled', models.BooleanField(db_index=True, default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 12, 19, 20, 13, 894598, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('voided', 'Voided')], db_index=True, default='posted', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='void_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(db_index=True, help_text="e.g. '1000-CASH'", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='entry',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='entry',
            name='transaction',
            field=models.ForeignKey(help_text='Parent transaction. Cascade delete is BLOCKED — use voids.', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='Reference to order ID, invoice, return, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['type', 'is_active'], name='finance_acc_type_d51131_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['account', 'created_at'], name='finance_ent_account_d90690_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['transaction'], name='finance_ent_transac_8daa74_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'timestamp'], name='finance_tra_status_b8ad93_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_id'], name='finance_tra_referen_043ee3_idx'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ledger_account',
            field=models.ForeignKey(help_text='Linked Chart of Accounts entry (e.g. 1000-CASH or 1010-BKASH)', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='finance.account'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_entry',
            field=models.ForeignKey(blank=True, help_text='Set when this bank transaction is reconciled to a ledger entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='finance.entry'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.bankstatement'),
        ),
        migrations.AlterUniqueTogether(
            name='bankstatement',
            unique_together={('bank_account', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['is_reconciled', 'statement'], name='finance_ban_is_reco_90a44f_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_date'], name='finance_ban_transac_168ec5_idx'),
        ),
    ]
