# Generated by Django 5.0.14 on 2026-07-08 19:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('voided', 'Voided')], db_index=True, default='posted', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='void_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(db_index=True, help_text="e.g. '1000-CASH'", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='entry',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='entry',
            name='transaction',
            field=models.ForeignKey(help_text='Parent transaction. Cascade delete is BLOCKED — use voids.', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, help_text='Reference to order ID, invoice, return, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['type', 'is_active'], name='finance_acc_type_d51131_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['account', 'created_at'], name='finance_ent_account_d90690_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['transaction'], name='finance_ent_transac_8daa74_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'timestamp'], name='finance_tra_status_b8ad93_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_id'], name='finance_tra_referen_043ee3_idx'),
        ),
    ]
