# Generated by Django 5.0.14 on 2026-07-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_update_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'bKash Business', 'DBBL Savings'", max_length=100)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('mobile_banking', 'Mobile Banking'), ('cash', 'Cash in Hand')], default='bank', max_length=20)),
                ('provider', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('upay', 'Upay'), ('dbbl', 'Dutch-Bangla Bank (DBBL)'), ('brac_bank', 'BRAC Bank'), ('dutch_bangla', 'Dutch Bangla'), ('islami_bank', 'Islami Bank'), ('city_bank', 'City Bank'), ('eastern_bank', 'Eastern Bank'), ('ucb', 'United Commercial Bank'), ('prime_bank', 'Prime Bank'), ('trust_bank', 'Trust Bank'), ('other', 'Other')], default='other', max_length=30)),
                ('account_number', models.CharField(help_text='Bank account no. or mobile number', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_account', models.ForeignKey(help_text='Linked Chart of Accounts entry (e.g. 1000-CASH or 1010-BKASH)', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='finance.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, help_text='Balance as per bank at start of period', max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, help_text='Balance as per bank at end of period', max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='finance.bankaccount')),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('bank_account', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(help_text="Bank's own description/narration", max_length=255)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Money In)'), ('debit', 'Debit (Money Out)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. Use transaction_type to determine direction.', max_digits=14)),
                ('reference', models.CharField(blank=True, default='', help_text='Cheque no., bKash TrxID, bank ref. etc.', max_length=100)),
                ('is_reconciled', models.BooleanField(db_index=True, default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_entry', models.ForeignKey(blank=True, help_text='Set when this bank transaction is reconciled to a ledger entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='finance.entry')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.bankstatement')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['is_reconciled', 'statement'], name='finance_ban_is_reco_90a44f_idx'), models.Index(fields=['transaction_date'], name='finance_ban_transac_168ec5_idx')],
            },
        ),
    ]
