# Generated by Django 5.0.14 on 2026-08-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='alt_text',
            field=models.CharField(blank=True, help_text='SEO alt text', max_length=255, null=True),
        ),
    ]
