# Generated by Django 5.0.14 on 2026-07-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_remove_review_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedPrintList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Auto-generated name: 'YYYY-MM-DD HH:MM:SS'. Editable by user.", max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text="Optional batch-level notes (e.g. 'Rush job for Eid collection').")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prepared Print List',
                'verbose_name_plural': 'Prepared Print Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name for this printing file, e.g. 'Skull Tee Front & Back'.", max_length=255)),
                ('design_file_1', models.FileField(help_text='Primary design image. Any format (PNG, JPG, PDF, AI, etc.).', upload_to='printing_designs/')),
                ('design_file_1_width_mm', models.PositiveIntegerField(default=0, help_text='Print width of design file 1, in millimetres (mm).')),
                ('design_file_1_height_mm', models.PositiveIntegerField(default=0, help_text='Print height of design file 1, in millimetres (mm).')),
                ('design_file_2', models.FileField(blank=True, help_text='Optional secondary design image (e.g. back print, sleeve label).', null=True, upload_to='printing_designs/')),
                ('design_file_2_width_mm', models.PositiveIntegerField(blank=True, help_text='Print width of design file 2, in millimetres (mm).', null=True)),
                ('design_file_2_height_mm', models.PositiveIntegerField(blank=True, help_text='Print height of design file 2, in millimetres (mm).', null=True)),
                ('additional_notes', models.TextField(blank=True, default='', help_text='Free-form instructions for the press operator. Fabric type, colour codes, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product this artwork belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='printing_files', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Printing File',
                'verbose_name_plural': 'Printing Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreparedPrintItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of prints required for this design in this batch.')),
                ('order_number', models.CharField(blank=True, default='', help_text='Informational: source order reference. No FK — keeps module independent.', max_length=50)),
                ('prepared_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='printing.preparedprintlist')),
                ('printing_file', models.ForeignKey(help_text='The design/artwork to print.', on_delete=django.db.models.deletion.PROTECT, related_name='print_items', to='printing.printingfile')),
            ],
            options={
                'verbose_name': 'Prepared Print Item',
                'verbose_name_plural': 'Prepared Print Items',
                'ordering': ['id'],
            },
        ),
    ]
