# Generated by Django 5.0.14 on 2026-07-01 08:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reward_type', models.CharField(choices=[('percent', 'Percentage Discount'), ('fixed', 'Fixed Discount'), ('freeship', 'Free Delivery'), ('membership', 'Membership Reward')], default='percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('membership_tier', models.CharField(blank=True, help_text='e.g. VIP, Platinum', max_length=50, null=True)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('per_customer_limit', models.PositiveIntegerField(default=1)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('banner_url', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromoUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('customer_phone', models.CharField(max_length=50)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='marketing.promocode')),
            ],
        ),
    ]
