# Generated by Django 5.0.14 on 2026-07-03 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_membershiptier_customerprofile_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(default='', help_text='Customer identity key', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='tier_assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
