# Generated by Django 5.0.14 on 2026-07-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_customerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
