# Generated by Django 5.0.14 on 2026-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customerprofile_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.URLField(blank=True, help_text='URL to customer profile image', null=True),
        ),
    ]
