# Generated by Django 5.0.14 on 2026-08-09 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customerprofile_profile_image'),
        ('orders', '0010_order_orders_orde_user_id_37fed6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['phone'], name='crm_custome_phone_8055d6_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['user'], name='crm_custome_user_id_c84681_idx'),
        ),
    ]
