# Generated by Django 5.0.14 on 2026-07-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_update_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='cover_art',
        ),
        migrations.RemoveField(
            model_name='track',
            name='cover_url',
        ),
    ]
