# Generated by Django 5.0.14 on 2026-07-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list, help_text='Float array — the semantic embedding vector for this product.')),
                ('model_name', models.CharField(default='text-embedding-3-small', help_text='The embedding model used to generate this vector. Track for version invalidation.', max_length=100)),
                ('source_text', models.TextField(blank=True, help_text='The exact text that was embedded. Stored for debugging and re-embed detection.')),
                ('embedded_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last embedding refresh.')),
                ('product', models.OneToOneField(help_text='The product this embedding vector belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Embedding',
                'verbose_name_plural': 'Product Embeddings',
            },
        ),
    ]
