# Generated by Django 5.0.14 on 2026-08-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_review_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['listing_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['listing_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['listing_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='listing_order',
            field=models.IntegerField(default=0, help_text='Used for manual display ordering (lower numbers appear first).'),
        ),
        migrations.AddField(
            model_name='product',
            name='listing_order',
            field=models.IntegerField(default=0, help_text='Used for manual display ordering (lower numbers appear first).'),
        ),
        migrations.AddField(
            model_name='review',
            name='listing_order',
            field=models.IntegerField(default=0, help_text='Used for manual display ordering (lower numbers appear first).'),
        ),
    ]
