# Generated by Django 5.0.14 on 2026-08-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['listing_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['listing_order', 'id']},
        ),
        migrations.AddField(
            model_name='brand',
            name='listing_order',
            field=models.IntegerField(default=0, help_text='Used for manual display ordering (lower numbers appear first).'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='listing_order',
            field=models.IntegerField(default=0, help_text='Used for manual display ordering (lower numbers appear first).'),
        ),
    ]
