# Generated by Django 5.0.14 on 2026-08-19 20:23

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_category_catalog_cat_slug_695af4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='SEO alt text for category image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to=apps.catalog.models.product_image_upload_path),
        ),
    ]
