# Generated by Django 5.0.14 on 2026-09-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_category_image_alt_text_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='choice_metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Metadata for choices, e.g., mapping choice 'Red' to '#FF0000' or an image URL"),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='display_style',
            field=models.CharField(choices=[('text', 'Text'), ('color', 'Color Swatch'), ('image', 'Image Swatch')], default='text', help_text='How this attribute should be displayed on the frontend', max_length=20),
        ),
    ]
