# Generated by Django 5.0.14 on 2026-09-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productattribute_choice_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeguidetemplate',
            name='tables',
            field=models.JSONField(blank=True, default=list, help_text="List of tables e.g. [{'name': 'Tees', 'headers': [...], 'rows': [...]}]"),
        ),
    ]
